language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - ruby-head
  - jruby-head
addons:
  code_climate:
    repo_token: 45dcce14bff5011d3d03eb8e7571b15f9a7538e277683246e90fd2bdcb8c3b7f